### ISSUE TITLE
How to generate FINAL_Real.ckpt and FINAL_Imag.ckpt files using GRUTraining?

### ISSUE THREAD

**Issue by thisislohith6** [ShinoharaYuuyoru/NoiseReductionUsingGRU#4]
Hi, I have followed all the steps to run the model as mentioned in the Readme file, but when I am executing the GRUTraining.py file it is not Generating FINAL_Real.ckpt and FINAL_Imag.ckpt files but when executing GRUModelTest.py it requires Real and Imag ckpt files. So how to generate these files. Could you please help me with this issue.

Here is list of file created when executing GRUTraining.py file :
1.checkpoints
2.FINAL.ckpt.data-00000-of-00001
3.FINAL.ckpt.index
4.FINAL.ckpt.meta

what should I do to generate real and imag file?

**Comment by ShinoharaYuuyoru** [comment]
Thank you for your great attention to my graduation project. It's my pleasure to see this can help you.

Note that I have already not seen this project for nearly two years, so I'm not very familiar with the code now.
I try my best to answer your questions by my memory, but I think you should verify my answers by yourself.

I think you have already ignored the files: LSTMTestTraining.py and ModelTest.py as I mentioned in the README.md because they work to create an LSTM model.
Then, let's concentrate on GRUTraining.py and look at the line 50 to 52 in the sequentialized_spectrum method:
        # Magnitude and Phase Spectra
        # Mag = Sxx.real
        Mag = Sxx.imag          # Get imaginary part of Sxx. This will try to get a imaginary model.
Actually, for spectrum analysis in audio processing, in my opinion, we should analyze the REAL number part and the IMAGINE number part of the spectrum.
This relates to the Digital Signal Process, Fourier Transformation. Please refer to related materials.
That is, I trained 2 kinds of models to fit the two parts separately by commenting/uncommenting line 51 and 52, to get Real and Imag ckpt files.
Then, these two ckpt files will be used in GRUModelTest.py finally.

Sorry for my poor codes and documentation.
May this explanation will help you.

**Comment by thisislohith6** [comment]
Thanks for your valuable time and hope this helps me.
